version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bddStokage
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-bddStokage.sql:/docker-entrypoint-initdb.d/init-bddStokage.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  mysql_secret:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secret-Key
    ports:
      - "3307:3306"
    volumes:
      - mysql-secret-data:/var/lib/mysql
      - ./init-secret-Key.sql:/docker-entrypoint-initdb.d/init-secret-Key.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  backend-app:
    build: ../backEnd
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mysql_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./src/cert:/etc/cert
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend-app:
    build: ../front-end
    ports:
      - "8080:80"
    depends_on:
      - backend-app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  reverse-proxy:
    build: ../reverseProxyUrl
    ports:
      - "3001:3001"
    depends_on:
      - backend-app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  mysql-data:
  mysql-secret-data:
