name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]


jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps: 
      - uses: https://github.com/actions/checkout@v4
      - name: Use Node.js
        uses: https://github.com/actions/setup-node@v3
        with:
          node-version: '21.5.0'
        working-directory: ./backEnd
      - run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
        working-directory: ./backEnd
      - run: npm ci
        working-directory: ./backEnd
      - run: npm run build
        working-directory: ./backEnd
        env:
          NODE_OPTIONS: --max_old_space_size=4096  
  published:
    runs-on: ubuntu-latest
    needs: build-backend
    if: gitea.ref == 'refs/heads/main'
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."git.netgraph.fr"]
      - uses: docker/login-action@v2  # Added login step
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          registry: "<my-private-unsecure-git-repository-ip-address>:5000"
      - name: Build and push Docker image  # Username/password not required here
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.netgraph.fr/raphael-co/api-create-bdd-on-docker:${{gitea.sha}},git.netgraph.fr/raphael-co/api-create-bdd-on-docker:latest"
 