name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Use Node.js
        uses: https://github.com/actions/setup-node@v3
        with:
          node-version: '21.5.0'
        working-directory: ./backEnd
      - run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
        working-directory: ./backEnd
      - run: npm ci
        working-directory: ./backEnd
      - run: npm run build
        working-directory: ./backEnd
        env:
          NODE_OPTIONS: --max_old_space_size=4096
